services:
  - type: web
    name: brother-pes
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: HOST=0.0.0.0 python server.py
    autoDeploy: true
